### ISSUE TITLE
New Laptop Image

### ISSUE THREAD

**Issue by boblmartens** [openSUSE/landing-page#105]
Could really use a new laptop image on the landing page with a modern example of what openSUSE looks like. Extra points if we have a rotating image with the various desktops available!

**Comment by sysrich** [comment]
Do you have a free licensed photo in mind we could use?

**Comment by boblmartens** [comment]
That's my problem, I don't have anything right now. I will try and scrounge something up.

**Comment by sysrich** [comment]
Thats OUR problem - I looked, and couldn't find any either ;)

**Comment by boblmartens** [comment]
Any idea if Fedora has access to something that we might be able to use?

https://getfedora.org/en/workstation/

**Comment by victorhck** [comment]
Maybe this it's useful:
- https://app.box.com/v/proyectopensuse/1/11204283509/98450766837/1

And changing the image showed in the "laptop" with one screenshot updated.

an image made by an openSUSE fan and free licensed (CC).
've phun!

PS: You can find more awesome work about openSUSE here: https://app.box.com/v/proyectopensuse

**Comment by victorhck** [comment]
or maybe we can reuse the current image Gimp'ed a bit with a new screenshot

![opensuse-laptop](https://cloud.githubusercontent.com/assets/1514206/20136892/a5a3c9a0-a677-11e6-8a0c-8a7afbb0ade9.jpg)

**Comment by heijligen** [comment]
Who has the copyright on the laptop image? When there are no issues I would make a pull request with a Gimped version of the image. 
https://github.com/heijligen/landing-page

**Comment by vinzv** [comment]
This seems to be fixed/obsolete. Could someone please close this issue?
