### ISSUE TITLE
Two months fixed code is still not published - How long

### ISSUE THREAD

**Issue by tigerfoot** [openSUSE/landing-page#106]
On actually www.o.o there's still previous fixed version in
https://github.com/openSUSE/landing-page/commit/349c70b534420d5a730d5b947f2ed719364785d3
+2 month ago.

How much time is needed to have a git pull on production website ?

**Comment by sysrich** [comment]
Please refer to recent openSUSE board meeting minutes

**Comment by lnussel** [comment]
the problem was resolved
