### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by victorhck** [openSUSE/landing-page#12]
I have two suggestions, what do you think about it?
1.- Place the button to switch languages at the top of the page
2.- Add a "Go to the top" and the bottom on the page

've phun!!

**Comment by cyntss** [comment]
Thank you! 
I will take the number two if that is fine with you. 
There are many websites showing the language switch at the top, but the most common use case is the bottom, at least im basing my opinion in www.playstation.com, paypal.com, and even google.com, but this one has a very complex user experience, took me like 5 minutes to change my language back to english once i changed it to german lol.

The explanation for this is, the nav in the header needs to have "very common" links. That means, links a person will be clicking more often. The language, is a one time setting you will configure for the very first time, and then never again. A person doesn't change the language all the time, unless is testing something or wants to see a translation into a different language, but it isnt the normal use case.

Please let me know if you have a stronger opinion in this topic and the reasons why you would put it at the top and in the case we can discuss it :+1:

**Comment by victorhck** [comment]
ok for me!! ;)

**Comment by cyntss** [comment]
I have just commited the changes adding the Go to Top button
