### ISSUE TITLE
Grammar error in Spanish translation

### ISSUE THREAD

**Issue by SergioAtSUSE** [openSUSE/landing-page#122]
current: `Si necesita lols paquetes de software más reciente,`

It should be: `Si necesita los paquetes de software más recientes,`

lols -> los
reciente -> recientes

I have tried to propose the changes as a pull request, but I got stopped by: #120 and #121

**Comment by lnussel** [comment]
Translations are not maintained here but https://l10n.opensuse.org/projects/landing-page/master/es/
Please log in there, you maybe able to change the translations directly. Thanks!

**Comment by SergioAtSUSE** [comment]
Hello @lnussel,

I did it, but I was following the steps from section [`contributing`](https://github.com/openSUSE/landing-page#do-you-want-to-contribute-by-providing-translations-for-the-new-opensuse-website) in the README file.

Are these steps wrong?
Did you automatically receive a notification when I changed the translation?

Regards.

**Comment by lnussel** [comment]
They are not wrong but also document what needs to be done to add a *new* language. In your case of a typo fix using weblate is sufficient. Feel free to adjust the instructions to make that more clear.

I don't receive notifications for translations fixes. I check the page every once in a while and merge if needed. Just ping me if you have changes.

**Comment by SergioAtSUSE** [comment]
ok, done: https://l10n.opensuse.org/translate/landing-page/master/es/?checksum=f20c38c66a79d45a0ab6d4fae6c846b8#history

**Comment by SergioAtSUSE** [comment]
Related PR: https://github.com/openSUSE/landing-page/pull/123
