### ISSUE TITLE
Independent Development Environment ? 

### ISSUE THREAD

**Issue by Evalle** [openSUSE/landing-page#13]
On the main page we have these lines:
"If you require the latest software stacks and Independent Development Environment". 
Maybe you mean Integrated Development Environment ? https://en.wikipedia.org/wiki/Integrated_development_environment. Because I can't find any mention of Independent Development Environment on the internet. Fix me if I wrong. 
Thank you.

**Comment by cyntss** [comment]
@ddemaio ?

**Comment by ddemaio** [comment]
Good question. I worked this with @sysrich, but I'm not sure. Thanks @Evalle I'll see what Richard has to say.

**Comment by ddemaio** [comment]
Ok. It's Integrated. Thx @Evalle

**Comment by Evalle** [comment]
@ddemaio no problem. I will create PR today that will change "Independent Development Environment" to "Integrated Development Environment" on index.html and on each <language>.json file.

**Comment by ddemaio** [comment]
Thank you @Evalle

**Comment by Evalle** [comment]
@ddemaio @cyntss 
This issue was fixed in https://github.com/cyntss/opensuse-landing-page/pull/20
