### ISSUE TITLE
Kiwi link is broken

### ISSUE THREAD

**Issue by pbielefeldt** [openSUSE/landing-page#138]
On opensuse.org, the link for Kiwi is "http://opensuse.github.io/kiwi/", but it should rather be "https://suse.github.io/kiwi/", as the opensuse one is a 404 page.

**Comment by preemeijer** [comment]
Yes. This is true. I've made a pull request for the a couple of days ago but I don't know if this is the correct way to address this issue: https://github.com/openSUSE/landing-page/pull/136

Cheers, Paul

**Comment by vinzv** [comment]
This is fixed. Could someone please close this issue?
