### ISSUE TITLE
Outdated copyright indication

### ISSUE THREAD

**Issue by ardovm** [openSUSE/landing-page#194]
Hello,

some web pages seem to have an older or outdated copyright indication, such as https://www.opensuse.org/ (2019) and https://get.opensuse.org/leap/ (2020)

I hope this helps. Greetings from the FrOSCon!

**Comment by cboltz** [comment]
Fixed with https://github.com/openSUSE/landing-page/pull/195 and https://github.com/openSUSE/get-o-o/pull/60

Thanks for creating the pull requests!
