### ISSUE TITLE
Diaspora Share button

### ISSUE THREAD

**Issue by Warlordfff** [openSUSE/landing-page#2]
Hi
it's me again :D . On the social media share button I would like to see a Diaspora share button. Many people around use Diaspora and although is not FB many of our contributors are in to it and well,we could use some extra social media exposure. I made a small research and here is a how to make a Diaspora button(http://nicktux.com/2013/07/09/create-a-diaspora-share-button-wordpress-com/) on wordpress, so that you won't spend more time than needed to do it. openSUSE has a Diaspora account and if you like it I will get back to you with the account details. To be honest I have to do some digging on to it but it is there and I will find it.
Hope you consider this change
regards
Kostas Koudaras

**Comment by cyntss** [comment]
@Warlordfff great! lets ask to the community manager if he wants to add a share button for facebook.. @ddemaio  what do you think?
In any case, i think the share button should be located at the bottom because we dont want to disrupt attention from the main information.

**Comment by ddemaio** [comment]
@cyntss - sounds like a wonderful idea. Let's do it.

**Comment by cyntss** [comment]
@ddemaio yes sir! :smile:

**Comment by tigerfoot** [comment]
@cyntss is it done ?

**Comment by ddemaio** [comment]
Hi Bruno,
It's done. We should have it published by Thursday.
v/r
Doug
Quoting Bruno Friedmann <notifications@github.com>:

**Comment by tigerfoot** [comment]
@ddemaio you mean the whole site, or just the diaspora button on this repo ?

**Comment by ddemaio** [comment]
T6he landing page.

**Comment by tigerfoot** [comment]
@ddemaio so the issue #33 I've opened yesterday is almost done
but by who then ?

**Comment by ddemaio** [comment]
Hi Bruno,
Hop on these threads. There are a few conversations taking place about  
implementations, which is causing a little delay. Richard should be  
close with the changes Adam made, but there is one design change that  
needs to take place dropping machinery from the page.
https://github.com/cyntss/opensuse-landing-page/pull/34#issuecomment-138967752
https://github.com/cyntss/opensuse-landing-page/pull/37#issuecomment-139000832

**Comment by cyntss** [comment]
I will be closing this issue since I analysed the website and there is no real need for a share button. The best place to position a share button would be inside the News (in the blog), but at the moment the landing page has no strategic space to implement this.
