### ISSUE TITLE
Counter doesn't show up for Leap 15.4 (incorrect browser cache usage?)

### ISSUE THREAD

**Issue by lkocman** [openSUSE/landing-page#201]
Hello

I do have a local instance that shows counter just fine.
The only diff is in package-lock.json and then one untracked file assets/js/langpack/tr.json 
I did not want to touch dependencies, I so I did avoid touching package-lock.

Any help is welcome (I'll be traveling to the conference tomorrow but I can try to help).

![Screenshot from 2022-05-31 22-39-56](https://user-images.githubusercontent.com/510119/171280840-5b097a03-9daf-4b81-a891-0f1448544998.png)

**Comment by lkocman** [comment]
@cboltz thoughts on this one?

**Comment by cboltz** [comment]
Just checked, and the countdown gets displayed. At least now - IIRC it was broken before, so maybe your last change fixed it?

**Comment by lkocman** [comment]
Very interesting. I think we need to somehow enfore purge of browser cache. A private window of chromium shows the counter, but that is simply not the case for simply a new tab in chromium.

Firefox showed the counter as well (but I have not really used it before on this installbase, so cache was clean).

![image](https://user-images.githubusercontent.com/510119/171342573-e2cffdb7-f274-4a9d-aa25-cd4eae4130e4.png)

**Comment by lkocman** [comment]
Ctrl+F5 fixes, it the standard reload (F4) doesn't.

**Comment by lkocman** [comment]
Interestingly I did receive report today from Vincent, that he still saw the RC and not 15.4 GA on opensuse.org. Refresh fixed it.

**Comment by ddemaio** [comment]
counter removed to make room for microos.
