### ISSUE TITLE
Error 500 when you try to go on the Update to Leap 15.4 link

### ISSUE THREAD

**Issue by fultux** [openSUSE/landing-page#205]
Hello, 
Apparently there might be an issue regarding a link on the main webpage at https://www.opensuse.org/.

![image](https://user-images.githubusercontent.com/68954556/172643385-4716b75b-20f8-4be6-924a-4a738bebda7c.png)

When you try to go to Update to Leap 15.4 you get the following message: 500 Internal Server Error

![image](https://user-images.githubusercontent.com/68954556/172643243-4f8cae51-ac7e-42e1-9087-23ac4f0c16ce.png)

**Comment by bittin** [comment]
Hey!
i was being clumpsy when trying to fix it and missed a " it will be fixed with the next refresh of the site in around 15 minutes sorry

**Comment by cboltz** [comment]
Fix is deployed
