### ISSUE TITLE
Missing pointer to microos.opensuse.org microsite from landing page

### ISSUE THREAD

**Issue by lkocman** [openSUSE/landing-page#216]
Hello,

we should create a pointer to[ microos.opensuse.org ](https://microos.opensuse.org/) microsite from the main opensuse.org landing page. There was quite an effort behind the page, and it's not really easy to find. Such link would much improve it's visibility.

![screenshot](https://user-images.githubusercontent.com/510119/195351872-a4b11707-1d28-4006-8291-2fea4165e711.png)

**Comment by thkukuk** [comment]
At the Image-Based Linux Summit last week in Berlin nearly nobody did know openSUSE MicroOS.
As result I tried to find MicroOS on opensuse.org, but there is no way to find MicroOS. So if people don't know that MicroOS exist, they will not find it.
And if people don't know that it exist, they will not use it. And it will be ignored by development of upstream projects, which is hitting us very serious currently.
So we really urgently need a simple way that everybody sees that we have MicroOS, even if they are not especially searching for it.

**Comment by ddemaio** [comment]
We will remove the Leap 15.4 link with the alex logo and replace it with microos. Have Leap twice on the page is redundant. Hopefully we can get this done soon. I'll try and work on it on 14.10.
