### ISSUE TITLE
Remove google fonts or host it locally on our server

### ISSUE THREAD

**Issue by ddemaio** [openSUSE/landing-page#220]
![Screenshot from 2022-10-27 21-25-19](https://user-images.githubusercontent.com/8996626/198380861-9aa89388-7b3a-436f-8e95-4bf98d445e41.png)

Based on this information, https://blog.runcloud.io/google-fonts-gdpr/ we will need to remove the google fonts (@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,700);) on line 1 of https://github.com/openSUSE/landing-page/blob/master/assets/css/opensuse-countdown.less to be complaint with new GDPR concerns with the font. The main point is "For Google to send you the font, it has to know where to send it first and that means collecting your IP address. That specific action is what violates GDPR " 

If we host is on our own servers, would we be ok? @hellcp

**Comment by hellcp** [comment]
Probably, but I don't know if legal questions are really something I should be answering myself, there are people more qualified for it

**Comment by ddemaio** [comment]
> 

Do you think removing it or replacing it will be a big issue? @cboltz do you have an opinion on this?

**Comment by hellcp** [comment]
Hosting them wouldn't be much of an issue, so replacing that sounds easy

**Comment by ddemaio** [comment]
The #221 build passed all the checks on removal. Not sure whether to merge or host.

**Comment by hellcp** [comment]
There are no checks that check what the page looks like, so it's not surprising
