### ISSUE TITLE
Espanish Translation 

### ISSUE THREAD

**Issue by victorhck** [openSUSE/landing-page#3]
Hi!
Great to see a way to see that modern, and cool landpage in spanish (I'm from spain!)
But, the translation it's a bit... "semi-robotic translation" ;)
I can't find a locale file with the strings to translate. I just find a js code that translate the text, but sorry I'm not a developer, so I can't find the way to improve the translation, and I would like.

've phun and continue doing a great job!!

**Comment by cyntss** [comment]
@victorhck when you have the PR merged please remember to close this issue. And thank you for your contribution.

**Comment by cyntss** [comment]
Solved in PR #6

**Comment by victorhck** [comment]
Ok, it's alredy closed!
