### ISSUE TITLE
Add Leap / Tumbleweed comparison table

### ISSUE THREAD

**Issue by aspiers** [openSUSE/landing-page#38]
It would be really useful to embed a simple table showing the differences between Leap and Tumbleweed, e.g.

  | Leap | Tumbleweed
--- | ---- | ------------------
Release cycle | Every n months | Continuous, rolling upgrades
Latest release | n/a (replaces openSUSE 13.2) | n/a
Next release | openSUSE Leap 42.1 | n/a
Testing | openQA, [insert other stuff here] | openQA [and other stuff?]

etc.

Maybe add a button in the centre immediately below the Leap / Tumbleweed sections which reveals the table as hidden content?

**Comment by sysrich** [comment]
I like the idea of something to help people decide, but I think we need to figure out what attributes of Leap and Tumbleweed matter to people.. the development model has only a limited interest and appeal

So I'd focus on attributes more like 'Software Versions - Leap. Major changes only will new releases. Tumbleweed - New versions as soon as they're ready and tested

I'm actually thinking a short guide, might be better than a comparison table.. we can split that in a few simple pargraphs

**Comment by aspiers** [comment]
Sure - the content of that table was just for the purposes of demonstrating the layout - I don't really know enough about them to come up with better content.

I'm sceptical that paragraphs of text are more effective than a simple comparison matrix, but I'm still willing to be convinced ;-)

**Comment by cyntss** [comment]
Looks good !

**Comment by cyntss** [comment]
I think this can be a feature coming up in the next months, this together with other changes, but I wouldn't  pause the publishing of the website because there will always be improvements suggested from people .. or at least that is how it should be :)

**Comment by mynameismevin** [comment]
I googled for this page exactly because I wanted to try openSUSE (I'm a Debian guy) to see what it's about, but I don't entirely understand the difference between Tumbleweed and Leap. +1 to the possibility of adding some more distinction on the landing/info pages.

**Comment by aspiers** [comment]
Mike Lloyd <notifications@github.com> wrote:
> I googled for this page exactly because I wanted to try openSUSE (I'm a Debian guy) to see what it's about, but I don't entirely understand the difference between Tumbleweed and Leap. +1 to the possibility of adding some more distinction on the landing/info pages.

I'm not sure why this last comment has vanished from the issue, but thanks a lot for the feedback validating my concerns!  Hopefully we can fix this soon!

**Comment by mynameismevin** [comment]
Ah yeah...I deleted it after seeing the "Read More" button which explained
enough for me; I didn't want there to be useless noise. That being said, I
still don't entirely understand the difference, but I do understand it
enough to pick one of them.

Mike.

On Thu, 10 Mar 2016 at 08:38 Adam Spiers <notifications@github.com> wrote:

> Mike Lloyd <notifications@github.com> wrote:
> > I googled for this page exactly because I wanted to try openSUSE (I'm a
> Debian guy) to see what it's about, but I don't entirely understand the
> difference between Tumbleweed and Leap. +1 to the possibility of adding
> some more distinction on the landing/info pages.
>
> I'm not sure why this last comment has vanished from the issue, but thanks
> a lot for the feedback validating my concerns! Hopefully we can fix this
> soon!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openSUSE/landing-page/issues/38#issuecomment-194908042>
> .
>
-- 
Mike Lloyd
U.S. Marine Corps, Comcast VIPER
Cell: 808-633-8998

**Comment by aspiers** [comment]
Thanks Mike.  I think it's clear that this topic could do with a bit more clarification.

**Comment by cyntss** [comment]
Hi Mike.

Thank you for the feedback. 
From my very personal point of view, I think the description for both products has been written very “structured” while what we could do is try to have a friendlier explanation just like other softwares are doing it. With a more friendly-MKT oriented text and in 1st person we might achieve better results.

I will speak about it with the people involved and come up with a good solution for it :)

Thank you again for raising the flag.. its always very helpful to know what our fellow users think at first when entering the website. We should be giving a good first impression to all of you :)

Cheers!



> On 10 Mar 2016, at 17:03, Adam Spiers <notifications@github.com> wrote:
> 
> Thanks Mike. I think it's clear that this topic could do with a bit more clarification.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/openSUSE/landing-page/issues/38#issuecomment-194925409>.
> 

--
Cynthia Sanchez.
Front-end developer and UI designer.
SUSE Linux GmbH
GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg)
Maxfeldstraße 5
90409 Nürnberg
Germany
