### ISSUE TITLE
Too many animations

### ISSUE THREAD

**Issue by sknorr** [openSUSE/landing-page#42]
First: The new page is really great and from my perspective a big improvement over the current one. So, yeah, great work.

I like animations ... but there shouldn't be too many, and they should be quick and simple. And they should be functional, in that they should show you where you are navigating.

With that said, I think there are a few areas where the landing page would profit from a little less animation:

* Clicking "More information" below the Leap/Tumbleweed heads leads to a very complicated animation. Maybe, instead, the headline could remain where it is and the information would pop out over the other half of the blue box. (Not sure if that would work well... But the current animation is definitely too much.)
* The fly-in of the OpenSUSE tools is a bit much. Maybe instead they could quickly fade in and then move a little to the right to their final position.
* The text animation of the fixed header when scrolling does not look fluid in Firefox/Linux. Possibly, this is better on other OSs. But since Linux users are one of the target groups, the animation could maybe be left out entirely.
* The border-bottom animation when hovering over the navigation links at the top takes far too long. Could work better with a shorter animation time.

**Comment by erleeman** [comment]
I agree with that.

**Comment by okurz** [comment]
+1

I think all four specific suggestions by @sknorr are very valuable and worthwile
