### ISSUE TITLE
quivering cursor and graphic effect on click boxes

### ISSUE THREAD

**Issue by pierre4l** [openSUSE/landing-page#43]
When hovering the mouse over the bottom edge of the More Information or Install TW/Leap boxes, the cursor suddenly has a seizure and starts dancing. The text in the paragraph above also displays shaking symptoms.

This occurs on my oS 13.1 64-bit install with FF40.0.3 and the nVidia proprietary driver. I don't see the same symptoms in Konqueror.

**Comment by cyntss** [comment]
lol that is a bit funny. I havent seen the effect in Chrome, Firefox and IE versions I have installed, but I will have a look at it soon :)

**Comment by Evalle** [comment]
Reproduced with FF 40.0.3 on openSUSE Tumblweed (I have Intel Graphic card on my laptop). There are no 'dancing' symptoms in Google Chrome 45.0.2454.93 :)
