### ISSUE TITLE
Back button, logo or Home link do not get me to the main page.

### ISSUE THREAD

**Issue by kbaikov** [openSUSE/landing-page#47]
Back button, logo or Home link do not get me to the main page.

Steps to reproduce:
1. go to the the main page: https://www.opensuse.org/
2. select leap or tumbleweed.
3. click Back button, logo or Home link 

Actual behavior: nothing happens, you remain on the same page with leap or tumble weed selected.
Expected behavior: i am taken to the page where i can again select leap or tumbleweed.

Note: a link "back to main page" works perfectly. I expect back, home and logo link to work the same

**Comment by cyntss** [comment]
Excellent point. Will work on this as soon as I have time :+1:

**Comment by cboltz** [comment]
For getting the back button to work, using location.hash should help. See
https://forum.jquery.com/topic/how-to-load-content-with-back-button-enable-and-refresh-using-ajax for an (untested) example.
