### ISSUE TITLE
Heavy CPU usage on the page caused by JS

### ISSUE THREAD

**Issue by andreat** [openSUSE/landing-page#5]
Hi,

I tried to access the page to see it after Douglas sent a request for translation, so to have an idea of the amount of work for providing the translation.

In order to be able to see the content of the page correctly, I had to enable javascript for the site. As a result, the browser started to use constantly around 60% of one core and X.org around 70% of the other core of my laptop. This happened with both Pale Moon and Firefox.
I tried also other browsers: Opera used around 95% of one core while chromium took around 95% of one core and 65% of the other.
If I disable javascript, parts of the page become unaccessible but at least my CPU is essentially idle. I don't know whether I have to report this as a different issue.

In my opinion this CPU usage is really too high for the page and it should be reduced considerably.

**Comment by cyntss** [comment]
@andreat thank you for reporting this. Another colleague tested it without javascript and it worked fine for him, but it might have happened that the computer used had very good resources and the CPU usage was unnoticeable. 
I will personally have a look at it.

**Comment by cyntss** [comment]
Fixed in commit https://github.com/cyntss/opensuse-landing-page/commit/41c670b2dc805af68a3db2afd0f4d492036178ff
