### ISSUE TITLE
text in conference section unreadable in Konqueror

### ISSUE THREAD

**Issue by cboltz** [openSUSE/landing-page#52]
When using Konqueror, the text in the conferences section is nearly unreadable (white on a "whitened" picture). Same for the button, but that at least gets a background color on hover. 

Interestingly the picture is displayed much darker in Firefox (so no problem there), but it would still be a good idea to get it fixed for Konqueror.

**Comment by cyntss** [comment]
We decided to only stand for the newest versions of popular browsers such Chrome, Firefox and IE (yes, unfortunately we will support it), as well as the latest versions shipped in the latest regular release of openSUSE

**Comment by cboltz** [comment]
Seriously? I'd guess Konqueror is quite popular among KDE users, and it's a pity that you don't want to support it. And since it uses webkit code as a base, this bug might also affect Apple users (Safari is also based on webkit).

Please re-think this decision.

**Comment by coolo** [comment]
konqueror's default is (afaik) still khtml, which is *not* webkit.

**Comment by cboltz** [comment]
I just did a fresh tumbleweed installation - and Konqueror uses webkit as default.

Actually that's a good thing because with khtml the page is not really useable (partly broken images ("data:" not supported?), overlays not working etc.) - but there's at least one positive detail: the overlay color on the conference picture is correct ;-)
