### ISSUE TITLE
Undefined fun with contribute code / hardware

### ISSUE THREAD

**Issue by cboltz** [openSUSE/landing-page#55]
The contribute code / hardware buttons have a funny behaviour.

Reproducer:
  - in the contribute section, click "code" to open the details
  - click the "code" circle two or three times - this will display "undefined" right of the circle
  - now close the details overlay and search for the "code" circle. I didn't find it anymore ;-)
  - for additional fun, you can do the same with "hardware"

**Comment by Evalle** [comment]
Yep, reproduced with Google Chrome 45.0.2454.99 and FF 40.0.3
