### ISSUE TITLE
Titles coming out of the bubble

### ISSUE THREAD

**Issue by cyntss** [openSUSE/landing-page#58]
![image](https://cloud.githubusercontent.com/assets/5013096/10018416/d6842a74-6136-11e5-9124-7f91cde42402.png)

**Comment by Evalle** [comment]
Hello @cyntss the same problem with russian version:
![opensuse_bug1](https://cloud.githubusercontent.com/assets/2839811/10039333/1e063906-61d1-11e5-8688-ea92ad52e5e0.png)

**Comment by cyntss** [comment]
@Evalle thank you! I will need to take into account the different translations and come up with a good solution. Hopefully this friday I will take care of that :smiley:
