### ISSUE TITLE
Mobile menu button does not (always) work

### ISSUE THREAD

**Issue by sknorr** [openSUSE/landing-page#64]
**Browsers:** Firefox for Android and Chrome for Android.
**Site:** The version 

**Issue:** 
There is no reliable way to open and close the hamburger menu in the browsers named above.
The click target of the mobile menu button (hamburger button) seems to somehow be in the left margin next to the icon.
(In desktop Firefox, the menu button works fine. Not sure why there is such a discrepancy.)

[Another slightly off-topic note: the menu button does not have enough space around it to be a good tap target. And the OpenSUSE logo is right next to the menu button which makes it easy to tap the wrong target. See also e.g. http://www.lukew.com/ff/entry.asp?1085 ]

**Comment by cyntss** [comment]
we should rather detect the "swipe" in touch devices, I believe will be the best option to solve this issue.

**Comment by cyntss** [comment]
This will be fixed in  https://github.com/openSUSE/landing-page/pull/102, but it is all included in https://github.com/openSUSE/landing-page/issues/94 So im closing this issue :)
