### ISSUE TITLE
Starting animation appearing twice

### ISSUE THREAD

**Issue by okurz** [openSUSE/landing-page#80]
Opening https://www.opensuse.org/ is causing the animation of the appearing and flying-down icons for Leap and Tumbleweed to be played twice together with a flickering of the page itself.

Observed using Firefox 42.0 on Leap

**Comment by bmwiedemann** [comment]
I can reproduce it here and found that the problem goes away when dropping the part with
script src="sdk.js" id="facebook-jssdk  (introduced via build/js/main.min.js )

**Comment by bisht-richa** [comment]
I have not been able to reproduce the error. As such I would like to know if you still face the exact issue reported earlier.

**Comment by bmwiedemann** [comment]
It looks different now. in chromium-51 the leap and tumbleweed icons nicely fall down from the top, but in firefox-46 they just appear in their final location.

**Comment by okurz** [comment]
I have firefox-47 on Leap 42.1 and it's looking ok so I guess it's fixed. Closing. Thanks.
